private ["_index"];
if(isNil "AVD_FNC_GETINDEX_INDEX") then {
    AVD_FNC_GETINDEX_INDEX = -1;
};
AVD_FNC_GETINDEX_INDEX = AVD_FNC_GETINDEX_INDEX + 1;
publicVariable "AVD_FNC_GETINDEX_INDEX";
AVD_FNC_GETINDEX_INDEX;